# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0002_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='useremail',
            new_name='user_email',
        ),
    ]
