# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20170428_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='useremail',
        ),
    ]
