# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20170428_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
