# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_user_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
