# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('env', models.CharField(max_length=20)),
                ('submit_method', models.CharField(max_length=20)),
            ],
        ),
    ]
