# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectConf',
            new_name='Project',
        ),
    ]
