# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0002_auto_20170512_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=20)),
                ('env', models.CharField(max_length=20)),
                ('submit_method', models.CharField(max_length=20)),
                ('repo', models.CharField(max_length=10)),
                ('repo_address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('repertory', models.CharField(max_length=100)),
                ('excludes_file', models.TextField(max_length=256)),
                ('www_user', models.CharField(max_length=20)),
                ('web_path', models.CharField(max_length=20)),
                ('deploy_releases', models.CharField(max_length=20)),
                ('releases_num', models.IntegerField(max_length=5)),
                ('servers', models.TextField(max_length=256)),
            ],
        ),
    ]
