# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0004_auto_20170513_0633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
