# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0005_delete_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconf',
            name='repo',
        ),
    ]
