# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0006_remove_projectconf_repo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectconf',
            old_name='password',
            new_name='p_password',
        ),
        migrations.RenameField(
            model_name='projectconf',
            old_name='username',
            new_name='p_username',
        ),
    ]
